### ISSUE TITLE
GitHub repo description is misspelled

### ISSUE THREAD

**Issue by eeree** [Abdizriel/generator-nodejs-microservice-starter#1]
Description of the repository is missing some characters at the very beginning.
Is: _enerator of (...)_
Should be: _Generator for (...)_
![Preview](https://cloud.githubusercontent.com/assets/1375008/16735989/7719efba-478b-11e6-8e48-c0c23369a7e4.png)

**Comment by Abdizriel** [comment]
@eeree Thanks for notice!
Fixed
